apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::300137940965:role/twahirwa-eks-cluster-default_node_group-20250301031727058300000011
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

  mapUsers: |
    - userarn: arn:aws:iam::300137940965:user/auth-service-user
      username: cluster-admin
      groups:
        - system:masters
