apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: 300137940965.dkr.ecr.us-east-1.amazonaws.com/auth-service:latest # verify this line
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: auth-service-secrets
