apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  type: LoadBalancer # or NodePort, depending on your setup
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
